# Borrowed from Write The Docs! (https://github.com/writethedocs/www/blob/master/vale/WTD/Abbreviations.yml)
extends: substitution
message: Use '%s'
ignorecase: false
level: warning
swap:
  '(?:eg)': e.g.,
  '(?:ie)': i.e.,
  '(?:e\.g\.)\s*': e.g.,
  '(?:i\.e\.)\s*': i.e.,