name: Issue Workflow

on: [issues]

jobs:
  greeting:
    name: Greetings to 1st time contributors
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'Congratulations on submitting your first issue to the San-Francisco-Write-The-Docs/www repository!'
  labels:
    name: Add help wanted label to unassigned issues
    runs-on: ubuntu-latest
    steps:
      - uses: andymckay/labeler@1.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          add-labels: "help wanted"
          ignore-if-assigned: true
  incompleteActions:
    name: Check issue for incomplete checklist items
    runs-on: ubuntu-latest
    steps:
      - uses: adamzolyak/checklist-checker-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}